#!/bin/bash

pokemons=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
max_jobs=3

for p in "${pokemons[@]}"; do
    echo "Fetching data for $p..."

    curl -s -f "https://pokeapi.co/api/v2/pokemon/${p}" -o "${p}.json" &

    while [ $(jobs -r | wc -l) -ge $max_jobs ]; do
        sleep 1
    done
done

# Suppose you want to kill all running jobs here (use with caution!)
echo "Killing all background jobs..."
jobs -p | xargs kill

wait  # wait for all jobs to exit

echo "All jobs killed and cleaned up."
