#!/bin/bash

pokemons=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

for p in "${pokemons[@]}"; do
    (
      echo "Extracting data for $p..."
      curl -s -f "https://pokeapi.co/api/v2/pokemon/${p}" -o "${p}.json" && \
      echo "Saved Pokemon data for $p to ${p}.json" || \
      echo "Failed to fetch data for $p"
    ) &
done

wait

echo "All downloads complete."